### ISSUE TITLE
AndroidX - nutný velký refactoring

### ISSUE THREAD

**Issue by stegeron** [stegeron/zonkoid#16]
Nejnovější verze Androida budou časem nekompatibilní s compat a support knihovnami. Ty budou nahrazeny Android X knihovnami, na webu google návod, jedná se většinou o package, ale dopad je i na resources, XML apod.

Znamenat to bude rozsáhlý refactoring.

**Comment by JohnyGQD** [comment]
Zatim jsem se ani u komplexnich projektu nesetkal s tim, ze by nefungovala automaticka migrace v Android Studiu. Smele do toho, revertovat se to da vzdycky :-).

**Comment by stegeron** [comment]
Už jsem to asi před půl rokem zkoušel v Android Studiu a přestože Zonkoid není zrovna komplexní projekt, tak automatická migrace způsobila spoustu nefunkčních obrazovek. Dopad byl i do resources, do XML apod, kde se také používají compat knihovny. Ale možná jsem na to šel špatně. 

Nechceš to zkusit? :)

**Comment by JohnyGQD** [comment]
Mně to připadá OK. Akorát jsem musel zapnout ještě multidex a povýšit compileSdkVersion na 28, aby AndroidX fungoval :-). Víc jsem se v tom nerýpal, udělám pull request a můžeš se podívat, jestli tam najdeš něco rozbitého.

**Comment by stegeron** [comment]
To by mozna chtelo samostatnou branch...

**Comment by JohnyGQD** [comment]
Já věděl, že jsem něco zapomněl :-). Na mé straně upraveno, na své si případně zedituj PR.

**Comment by stegeron** [comment]
Hotovo, na p4m problém založena jiná chyba.
